"""Static asset references."""

# Content hash of the bundled sprite sheet, used for cache busting in the
# asset URL. Regenerated by the build, not a credential.
SPRITE_BUNDLE_HASH = "d8f3a1c07b9e4526af13cc80e5b7d249f6a0b3e18c74d295"

SPRITE_URL = f"/static/sprites.{SPRITE_BUNDLE_HASH}.png"
